export type Quiz = { question: string; answers: string[]; correct: number; hint: string; explain: string };
export const days = [
{day:1,title:"DNA 샘플 복구",area:"기초 연구동",task:"선배 연구원 미나에게 말을 걸어 DNA 퀴즈를 해결하세요.",reward:"현미경실 설계도"},{day:2,title:"세포의 하루",area:"현미경실",task:"세포 분열 단계를 관찰하고 올바른 순서로 배열하세요.",reward:"효모 배양 키트"},{day:3,title:"보이지 않는 이웃",area:"배양실",task:"효모 배양 조건을 정하고 오염 여부를 판별하세요.",reward:"PCR 장비 설계도"},{day:4,title:"DNA를 늘려라",area:"PCR실",task:"PCR의 세 온도 단계를 올바르게 설정하세요.",reward:"자동 관수기"},{day:5,title:"아픈 토마토",area:"온실",task:"병든 잎을 채취하고 원인을 추론하세요.",reward:"조직배양실"},{day:6,title:"하나의 잎, 새로운 개체",area:"조직배양실",task:"호르몬 균형을 조절해 건강한 묘목을 만드세요.",reward:"유전자 분석실"},{day:7,title:"BIO LAB 프로젝트",area:"중앙 연구동",task:"재배·DNA·PCR·배양 지식을 활용해 작물 질병을 해결하세요.",reward:"봄 연구 인증서"}];
export const quizzes: Quiz[] = [
{question:"DNA 가닥 5′-ATGC-3′와 상보적으로 결합하는 염기서열은?",answers:["5′-ATGC-3′","3′-TACG-5′","3′-UACG-5′","5′-GCTA-3′"],correct:1,hint:"DNA에서 A는 T와, G는 C와 결합해요.",explain:"두 DNA 가닥은 반대 방향으로 놓이며 A–T, G–C가 상보적으로 결합합니다."},
{question:"세포 분열 전 DNA가 복제되는 가장 중요한 이유는?",answers:["세포를 크게 만들기 위해","두 딸세포에 같은 유전정보를 전달하기 위해","에너지를 만들기 위해","세포막을 제거하기 위해"],correct:1,hint:"분열 뒤 만들어지는 두 세포가 무엇을 받아야 할지 생각해 보세요.",explain:"DNA 복제는 두 딸세포가 동일한 유전정보를 갖도록 준비하는 과정입니다."},
{question:"효모 배양액이 예상과 다른 색과 냄새를 보입니다. 가장 먼저 의심할 것은?",answers:["광합성","오염","DNA 복제","감수분열"],correct:1,hint:"원하지 않는 미생물이 들어왔을 가능성을 생각해 보세요.",explain:"배양에서는 무균 조작과 오염 확인이 중요합니다. 이상 변화는 오염의 신호일 수 있습니다."},
{question:"PCR의 올바른 기본 순서는?",answers:["신장–결합–변성","변성–결합–신장","결합–변성–신장","변성–신장–결합"],correct:1,hint:"먼저 두 DNA 가닥을 분리한 뒤 프라이머를 붙입니다.",explain:"PCR은 변성, 프라이머 결합, 신장 단계를 반복해 표적 DNA를 증폭합니다."},
{question:"질소 영양액을 지나치게 많이 준 식물에서 나타날 수 있는 현상은?",answers:["항상 열매가 많아진다","잎은 무성하지만 꽃과 열매가 줄 수 있다","DNA가 사라진다","물을 전혀 흡수하지 않는다"],correct:1,hint:"잎과 줄기의 성장과 열매 생산은 항상 같은 방향일까요?",explain:"질소 과다는 영양생장을 지나치게 촉진해 개화와 결실에 불리할 수 있습니다."},
{question:"조직배양에서 상대적으로 옥신 비율이 높을 때 기대할 수 있는 변화는?",answers:["뿌리 형성","과일 숙성","DNA 절단","잎의 증산 중단"],correct:0,hint:"옥신은 삽목에서도 이 기관의 형성을 돕습니다.",explain:"일반적으로 상대적으로 높은 옥신 조건은 뿌리 형성을, 높은 사이토키닌 조건은 새싹 형성을 촉진할 수 있습니다."},
{question:"CRISPR에서 가이드 RNA의 주요 역할은?",answers:["세포에 물 공급","표적 DNA 위치 안내","단백질을 분해","세포벽 생성"],correct:1,hint:"‘가이드’라는 이름처럼 유전자 가위를 어디로 데려갈까요?",explain:"가이드 RNA는 상보적인 염기서열을 인식해 Cas 단백질을 표적 DNA 위치로 안내합니다."}];
export const crops=[{id:"arab",name:"애기장대",icon:"🌱",days:2,desc:"생장 주기가 짧은 대표적인 식물 연구 모델"},{id:"pea",name:"완두콩",icon:"🫛",days:3,desc:"유전 형질을 관찰하기 좋은 작물"},{id:"tomato",name:"토마토",icon:"🍅",days:4,desc:"질병 진단과 숙성 연구에 사용"},{id:"berry",name:"딸기",icon:"🍓",days:4,desc:"조직배양과 영양 조건 연구에 사용"}];
export const treatments=[{id:"water",name:"기본 배양액",effect:"안정적인 생장",learn:"대조군의 기준"},{id:"gib",name:"지베렐린",effect:"발아·줄기 신장 +1",learn:"빠른 신장이 건강한 생장과 같지는 않음"},{id:"auxin",name:"옥신",effect:"뿌리 발달 +1",learn:"농도와 조직에 따라 작용이 달라짐"},{id:"cyto",name:"사이토키닌",effect:"새싹·세포분열 +1",learn:"옥신과의 비율이 기관 형성에 중요"},{id:"nitrogen",name:"질소 영양액",effect:"잎 생장 +1",learn:"과량이면 개화·결실에 불리"}];
export const equipment=[{id:"scope",name:"디지털 현미경",cost:80,unlock:1,desc:"세포 분열 퀘스트를 해금합니다."},{id:"incubator",name:"소형 배양기",cost:120,unlock:2,desc:"효모와 식물 세포 배양을 시작합니다."},{id:"pcr",name:"PCR 기기",cost:180,unlock:3,desc:"DNA 증폭 연구를 시작합니다."},{id:"irrigation",name:"자동 관수기",cost:150,unlock:4,desc:"매일 모든 작물에 자동으로 물을 줍니다."},{id:"culture",name:"조직배양대",cost:220,unlock:5,desc:"식물 조직에서 새 묘목을 만듭니다."}];
