"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {crops,days,equipment,quizzes,treatments} from "./game-data";
type Screen="title"|"creator"|"game"; type Plot={crop:string|null;age:number;watered:boolean;treatment:string;ready:boolean};
type Save={name:string;hair:number;coat:number;specialty:string;day:number;rp:number;materials:number;level:number;xp:number;plots:Plot[];owned:string[];quizDone:boolean[];notebook:string[]};
const fresh=():Save=>({name:"새봄",hair:0,coat:0,specialty:"분자생물학",day:1,rp:60,materials:4,level:1,xp:0,plots:Array.from({length:8},()=>({crop:null,age:0,watered:false,treatment:"water",ready:false})),owned:[],quizDone:Array(7).fill(false),notebook:[]});
const hairs=["#533425","#e9b949","#26364a","#8c3f62"],coats=["#f6f1dd","#7fc7c4","#ef9f8f","#8ea9d8"];
function Person({hair,coat,big=false}:{hair:number;coat:number;big?:boolean}){return <span className={`person ${big?"big":""}`} style={{"--hair":hairs[hair],"--coat":coats[coat]} as React.CSSProperties}><i/><b/><em/></span>}

export default function Home(){
 const [screen,setScreen]=useState<Screen>("title"),[save,setSave]=useState<Save>(fresh()),[modal,setModal]=useState<string|null>(null),[talk,setTalk]=useState<string|null>(null),[answer,setAnswer]=useState<number|null>(null),[result,setResult]=useState<"right"|"wrong"|null>(null),[near,setNear]=useState<string|null>(null),[toast,setToast]=useState("");
 const canvas=useRef<HTMLCanvasElement>(null),pos=useRef({x:320,y:270}),keys=useRef<Record<string,boolean>>({}); const current=days[save.day-1]||days[6];
 const persist=useCallback((n:Save)=>{setSave(n);localStorage.setItem("biolab-save",JSON.stringify(n))},[]); const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2100)};
 const hasSave=()=>typeof window!=="undefined"&&!!localStorage.getItem("biolab-save");
 const draw=useCallback(()=>{const c=canvas.current;if(!c)return;const x=c.getContext("2d")!;x.imageSmoothingEnabled=false;
  for(let yy=0;yy<360;yy+=20)for(let xx=0;xx<640;xx+=20){x.fillStyle=(xx/20+yy/20)%2?"#8fc2a7":"#95c8ad";x.fillRect(xx,yy,20,20)}
  x.fillStyle="#d8bd82";x.fillRect(0,248,640,60);x.fillRect(282,80,76,280);for(let xx=0;xx<640;xx+=20){x.fillStyle=xx%40?"#c8a96e":"#e4ca91";x.fillRect(xx,266,20,8)}
  x.fillStyle="#603f34";x.fillRect(28,48,214,132);x.fillStyle="#d78658";x.fillRect(36,58,198,112);x.fillStyle="#315d5a";x.fillRect(22,42,226,24);x.fillStyle="#173e3c";x.fillRect(100,126,50,54);x.fillStyle="#f2d57d";x.fillRect(51,92,36,30);x.fillRect(172,92,36,30);x.fillStyle="#fff1c9";x.fillRect(92,72,66,34);x.fillStyle="#3b786d";x.font="bold 13px monospace";x.fillText("BIO LAB",98,94);
  x.fillStyle="#315d5a";x.fillRect(415,80,190,108);x.fillStyle="#aee0d4";x.fillRect(422,88,176,92);x.strokeStyle="#4e8178";x.lineWidth=4;for(let q=430;q<600;q+=28){x.beginPath();x.moveTo(q,88);x.lineTo(q,180);x.stroke()}x.fillStyle="#315d5a";x.fillRect(490,136,40,44);
  save.plots.forEach((p,i)=>{const px=390+(i%4)*56,py=214+Math.floor(i/4)*58;x.fillStyle="#6b432c";x.fillRect(px,py,46,42);x.fillStyle=p.watered?"#493021":"#805238";x.fillRect(px+4,py+4,38,34);if(p.crop){x.fillStyle=p.ready?"#f0bd43":p.age?"#397d4d":"#6ca958";x.fillRect(px+20,py+8,7,26);x.fillRect(px+11,py+12,15,10);x.fillRect(px+24,py+17,14,10)}});
  x.fillStyle="#5aa2b1";x.fillRect(30,218,120,70);x.fillStyle="#9cd4d1";x.fillRect(40,228,100,50);x.fillStyle="#dfe9da";x.fillRect(170,213,72,62);x.fillStyle="#617f79";x.fillRect(180,223,52,42);x.fillStyle="#b7e9dd";x.fillRect(190,231,32,20);
  x.fillStyle="#75452e";x.fillRect(202,174,16,7);x.fillStyle="#efc3a4";x.fillRect(204,181,12,10);x.fillStyle="#fff4dc";x.fillRect(200,191,20,22);x.fillStyle="#2a3d45";x.fillRect(202,213,6,9);x.fillRect(212,213,6,9);
  save.owned.forEach((_,i)=>{x.fillStyle="#314f52";x.fillRect(260+i*28,115,22,30);x.fillStyle="#78c8c4";x.fillRect(265+i*28,120,12,13)});const p=pos.current;x.fillStyle=hairs[save.hair];x.fillRect(p.x-8,p.y-15,16,8);x.fillStyle="#efc3a4";x.fillRect(p.x-6,p.y-8,12,9);x.fillStyle=coats[save.coat];x.fillRect(p.x-9,p.y+1,18,20);x.fillStyle="#223b43";x.fillRect(p.x-8,p.y+21,6,8);x.fillRect(p.x+2,p.y+21,6,8)},[save]);
 useEffect(()=>{if(screen!=="game")return;let id=0,last=0;const loop=(t:number)=>{const d=Math.min(2,(t-last)/16||1);last=t;const p=pos.current,s=2.1*d;if(keys.current.ArrowUp||keys.current.w)p.y-=s;if(keys.current.ArrowDown||keys.current.s)p.y+=s;if(keys.current.ArrowLeft||keys.current.a)p.x-=s;if(keys.current.ArrowRight||keys.current.d)p.x+=s;p.x=Math.max(10,Math.min(630,p.x));p.y=Math.max(185,Math.min(342,p.y));setNear(Math.hypot(p.x-210,p.y-205)<48?"미나 선배":Math.hypot(p.x-470,p.y-250)<90?"재배 구역":Math.hypot(p.x-205,p.y-245)<58?"배양대":null);draw();id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);return()=>cancelAnimationFrame(id)},[screen,draw]);
 const interact=useCallback((t:string)=>{if(t==="미나 선배")setTalk(save.quizDone[save.day-1]?`오늘 연구는 완료했어. 보상 ‘${current.reward}’도 확인해 봐!`:`${save.name}, 오늘 임무는 ‘${current.title}’이야. ${current.task}`);else setModal(t==="재배 구역"?"greenhouse":"culture")},[save,current]);
 useEffect(()=>{const dn=(e:KeyboardEvent)=>{keys.current[e.key]=true;if(e.key===" "&&near){e.preventDefault();interact(near)}};const up=(e:KeyboardEvent)=>{keys.current[e.key]=false};addEventListener("keydown",dn);addEventListener("keyup",up);return()=>{removeEventListener("keydown",dn);removeEventListener("keyup",up)}},[near,interact]);
 const check=()=>{if(answer===null)return;const q=quizzes[save.day-1],ok=answer===q.correct;setResult(ok?"right":"wrong");if(ok&&!save.quizDone[save.day-1]){const done=[...save.quizDone];done[save.day-1]=true;persist({...save,rp:save.rp+100,materials:save.materials+2,xp:save.xp+35,quizDone:done,notebook:[...save.notebook,q.explain]})}};
 const plant=(i:number,crop:string)=>{if(save.materials<1)return notify("실험 재료가 부족합니다.");const p=[...save.plots];p[i]={crop,age:0,watered:false,treatment:"water",ready:false};persist({...save,materials:save.materials-1,plots:p})}; const changePlot=(i:number,patch:Partial<Plot>)=>{const p=[...save.plots];p[i]={...p[i],...patch};persist({...save,plots:p})};
 const nextDay=()=>{const plots=save.plots.map(p=>{if(!p.crop)return p;const age=p.age+(p.watered?1:0)+(p.treatment==="gib"?1:0),need=crops.find(c=>c.id===p.crop)?.days||3;return{...p,age,watered:save.owned.includes("irrigation"),ready:age>=need}});persist({...save,day:Math.min(7,save.day+1),plots});notify(`DAY ${Math.min(7,save.day+1)} 시작`)};
 const buy=(id:string,cost:number)=>{if(save.rp<cost)return notify("RP가 부족합니다.");if(!save.owned.includes(id)){persist({...save,rp:save.rp-cost,owned:[...save.owned,id]});notify("연구 장비 설치 완료!")}};

 if(screen==="title")return <main className="title"><div className="sky"/><h1><span>BIO</span><b>LAB</b></h1><div className="scene"><div className="mini lab">⚗</div><div className="path"><Person hair={0} coat={0} big/></div><div className="mini greenhouse">♧</div></div><nav><button onClick={()=>setScreen("creator")}>🌱 새로운 연구</button><button disabled={!hasSave()} onClick={()=>{const r=localStorage.getItem("biolab-save");if(r){setSave(JSON.parse(r));setScreen("game")}}}>🧬 이어하기</button><button onClick={()=>setModal("help")}>⚙ 설정·도움말</button></nav><p className="foot">LIFE SCIENCE RPG · SPRING RESEARCH</p>{modal==="help"&&<Simple title="플레이 방법" close={()=>setModal(null)}><p>방향키 또는 WASD로 이동하고, NPC나 시설 가까이에서 Spacebar를 누르세요. 진행 상황은 자동 저장됩니다.</p></Simple>}</main>;
 if(screen==="creator")return <main className="creator"><section><p className="eyebrow">NEW RESEARCHER</p><h1>연구원 등록</h1><p>당신의 모습과 첫 연구 분야를 선택하세요.</p><div className="creator-body"><div className="preview"><Person hair={save.hair} coat={save.coat} big/><b>{save.name||"이름 없음"}</b></div><div className="options"><label>연구원 이름<input maxLength={8} value={save.name} onChange={e=>setSave({...save,name:e.target.value})}/></label><Picker title="헤어 컬러" colors={hairs} value={save.hair} set={n=>setSave({...save,hair:n})}/><Picker title="연구복 컬러" colors={coats} value={save.coat} set={n=>setSave({...save,coat:n})}/><fieldset><legend>연구 분야</legend><div className="specialties">{["분자생물학","세포공학","바이오인포매틱스","의생명학"].map(s=><button key={s} className={save.specialty===s?"active":""} onClick={()=>setSave({...save,specialty:s})}>{s}</button>)}</div></fieldset></div></div><button className="primary" onClick={()=>{persist(save);setScreen("game")}}>BIO LAB 입소하기 →</button></section></main>;
 return <main className="game"><header><div className="profile"><Person hair={save.hair} coat={save.coat}/><span><b>{save.name}</b><small>Lv.{save.level} · {save.specialty}</small></span></div><div className="resources"><span>🧪 {save.materials}</span><span>RP {save.rp}</span><span>DAY {save.day} · SPRING</span></div><button onClick={()=>setModal("menu")}>☰</button></header><div className="layout"><div className="canvas"><canvas ref={canvas} width="640" height="360" aria-label="BIO LAB 연구소 지도"/>{near&&<div className="interact">SPACE · {near}</div>}<Pad keys={keys} action={()=>near&&interact(near)}/></div><aside><p className="eyebrow">MAIN QUEST · DAY {save.day}</p><h2>{current.title}</h2><mark>{current.area}</mark><p>{current.task}</p><div className="progress"><i style={{width:save.quizDone[save.day-1]?"100%":"35%"}}/></div><small>{save.quizDone[save.day-1]?"완료 · "+current.reward:"진행 중"}</small><div className="quick"><button onClick={()=>setModal("greenhouse")}>🌱 온실</button><button onClick={()=>setModal("equipment")}>🔬 장비</button><button onClick={()=>setModal("notebook")}>📖 도감</button></div>{save.quizDone[save.day-1]&&save.day<7&&<button className="end" onClick={nextDay}>연구 일지 작성 후 취침</button>}{save.day===7&&save.quizDone[6]&&<div className="ending">🏆 봄 연구 프로젝트 완료!</div>}</aside></div>{toast&&<div className="toast">{toast}</div>}
 <Dialog open={!!talk} onOpenChange={o=>!o&&setTalk(null)}><DialogContent className="pixel-modal" showCloseButton={false}><DialogHeader><DialogTitle>미나 선배 연구원</DialogTitle><DialogDescription>{talk}</DialogDescription></DialogHeader><div className="actions">{!save.quizDone[save.day-1]&&<button className="primary" onClick={()=>{setTalk(null);setAnswer(null);setResult(null);setModal("quiz")}}>퀘스트 수락</button>}<button onClick={()=>setTalk(null)}>나중에</button></div></DialogContent></Dialog>
 {modal==="quiz"&&<Quiz day={save.day} answer={answer} setAnswer={setAnswer} result={result} check={check} close={()=>setModal(null)}/>} {modal==="greenhouse"&&<Greenhouse save={save} plant={plant} change={changePlot} close={()=>setModal(null)} notify={notify}/>} {modal==="equipment"&&<Equipment save={save} buy={buy} close={()=>setModal(null)}/>} {modal==="notebook"&&<Notebook save={save} close={()=>setModal(null)}/>} {modal==="culture"&&<Culture day={save.day} close={()=>setModal(null)}/>} {modal==="menu"&&<Simple title="연구소 메뉴" close={()=>setModal(null)}><div className="menu"><button onClick={()=>setScreen("title")}>타이틀 화면으로</button><button onClick={()=>{localStorage.removeItem("biolab-save");setSave(fresh());setScreen("title")}}>저장 데이터 초기화</button></div></Simple>}</main>
}
function Picker({title,colors,value,set}:{title:string;colors:string[];value:number;set:(n:number)=>void}){return <fieldset><legend>{title}</legend><div className="swatches">{colors.map((c,i)=><button aria-label={`${title} ${i+1}`} key={c} className={value===i?"selected":""} style={{background:c}} onClick={()=>set(i)}/>)}</div></fieldset>}
function Pad({keys,action}:{keys:React.MutableRefObject<Record<string,boolean>>;action:()=>void}){const B=({k,label}:{k:string;label:string})=><button onPointerDown={()=>keys.current[k]=true} onPointerUp={()=>keys.current[k]=false} onPointerLeave={()=>keys.current[k]=false}>{label}</button>;return <div className="pad"><B k="ArrowUp" label="▲"/><B k="ArrowLeft" label="◀"/><B k="ArrowDown" label="▼"/><B k="ArrowRight" label="▶"/><button className="a" onClick={action}>A</button></div>}
function Simple({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <Dialog open onOpenChange={o=>!o&&close()}><DialogContent className="pixel-modal"><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader>{children}</DialogContent></Dialog>}
function Quiz({day,answer,setAnswer,result,check,close}:{day:number;answer:number|null;setAnswer:(n:number)=>void;result:string|null;check:()=>void;close:()=>void}){const q=quizzes[day-1];return <Simple title="BIO QUIZ" close={close}><h3>{q.question}</h3><div className="answers">{q.answers.map((a,i)=><button className={answer===i?"chosen":""} disabled={result==="right"} onClick={()=>setAnswer(i)} key={a}>{i+1}. {a}</button>)}</div>{result&&<div className={`feedback ${result}`}><b>{result==="right"?"정답입니다! RP +100":"아직 아니에요. 다시 생각해 봅시다."}</b><p>{result==="right"?q.explain:q.hint}</p></div>}<button className="primary" onClick={result==="right"?close:check}>{result==="right"?"연구소로 돌아가기":"정답 제출"}</button></Simple>}
function Greenhouse({save,plant,change,close,notify}:{save:Save;plant:(i:number,c:string)=>void;change:(i:number,p:Partial<Plot>)=>void;close:()=>void;notify:(s:string)=>void}){const [sel,setSel]=useState(0),p=save.plots[sel];const harvest=()=>{change(sel,{crop:null,age:0,watered:false,treatment:"water",ready:false});notify("수확 완료 · 재료와 연구 기록을 확보했습니다")};return <Simple title="바이오 온실" close={close}><div className="plots">{save.plots.map((q,i)=><button key={i} onClick={()=>setSel(i)} className={`${sel===i?"selected":""} ${q.watered?"wet":""}`}><span>{q.crop?crops.find(c=>c.id===q.crop)?.icon:"＋"}</span><small>{q.ready?"수확 가능":q.crop?`${q.age}일 성장`:"빈 재배대"}</small></button>)}</div>{!p.crop?<><p>심을 종자 선택 · 재료 1개</p><div className="crop-list">{crops.map(c=><button key={c.id} onClick={()=>plant(sel,c.id)}><b>{c.icon} {c.name}</b><small>{c.desc}</small></button>)}</div></>:<div className="plot-control"><h3>{crops.find(c=>c.id===p.crop)?.name}</h3>{p.ready?<button className="primary" onClick={harvest}>수확하기</button>:<button disabled={p.watered} onClick={()=>change(sel,{watered:true})}>{p.watered?"오늘 물주기 완료":"💧 물주기"}</button>}<select value={p.treatment} onChange={e=>change(sel,{treatment:e.target.value})}>{treatments.map(t=><option value={t.id} key={t.id}>{t.name} · {t.effect}</option>)}</select><p className="learning">💡 {treatments.find(t=>t.id===p.treatment)?.learn}</p></div>}</Simple>}
function Equipment({save,buy,close}:{save:Save;buy:(id:string,c:number)=>void;close:()=>void}){return <Simple title="연구 장비 상점" close={close}><p>보유 <b>{save.rp} RP</b></p><div className="shop">{equipment.map(e=><article key={e.id} className={save.day<e.unlock?"locked":""}><div><b>{e.name}</b><p>{e.desc}</p></div><button disabled={save.day<e.unlock||save.owned.includes(e.id)} onClick={()=>buy(e.id,e.cost)}>{save.owned.includes(e.id)?"설치 완료":save.day<e.unlock?`DAY ${e.unlock} 해금`:`${e.cost} RP`}</button></article>)}</div></Simple>}
function Notebook({save,close}:{save:Save;close:()=>void}){return <Simple title="연구 도감" close={close}><div className="notebook"><p>발견한 개념 {save.notebook.length}/7</p>{save.notebook.length?save.notebook.map((n,i)=><article key={i}><b>RECORD {String(i+1).padStart(2,"0")}</b><p>{n}</p></article>):<p className="empty">퀘스트를 해결하면 관찰 기록이 쌓입니다.</p>}</div></Simple>}
function Culture({day,close}:{day:number;close:()=>void}){return <Simple title="배양 관찰대" close={close}><div className="petri"><i/><i/><i/><i/><i/></div><h3>{day<3?"아직 배양 키트가 없습니다.":"효모 배양 · 관찰 중"}</h3><p>{day<3?"DAY 3 퀘스트에서 배양실을 복구할 수 있습니다.":"배지는 영양분을 제공하고, 적절한 온도와 무균 조작은 안정적인 배양에 중요합니다."}</p></Simple>}
